---
- name: Install Homebrew and Homebrew packages
  connection: local
  hosts: localhost
  vars:
    homebrew_casks:
      - iterm2
      - docker
      - google-cloud-sdk
      - visual-studio-code
      - postman
      - dbeaver-community
    homebrew_packages:
      - kubectl
      - terraform
      - node
      - dockutil
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-completions
  vars_files:
    - ../vars.yml
  tasks:
    - name: Install Homebrew # Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Add homebrew to Path Step 1
      shell: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/{{username}}/.zprofile
    - name: Add homebrew to Path Step 2
      shell: eval "$(/opt/homebrew/bin/brew shellenv)"
    - name: Install Homebrew casks
      homebrew_cask:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_casks}}"
    
    - name: Install zsh-autosuggestions
      homebrew:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_packages}}"
    