---
- name: Install Homebrew and Homebrew packages
  connection: local
  become: yes
  become_user: {{username}}
  vars_files:
    - ../vars.yml
  tasks:
    - name: Install Homebrew # Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Add homebrew to Path Step 1
      shell: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/{{username}}/.zprofile
    - name: Add homebrew to Path Step 2
      shell: eval "$(/opt/homebrew/bin/brew shellenv)"
    - name: Install iterm2
      homebrew_cask:
        state: present
        name: iterm2
    - name: Install Docker Desktop
      homebrew_cask:
        state: present
        name: docker
    - name: Install kubectl
      homebrew:
        state: present
        name: kubectl
    - name: Install gcloud
      homebrew_cask:
        state: present
        name: google-cloud-sdk
    - name: Install Terraform
      homebrew:
        state: present
        name: terraform
    - name: Install Visual Studio Code
      homebrew_cask:
        state: present
        name: visual-studio-code
    - name: Install NodeJS and NPM
      homebrew:
        state: present
        name: node
    - name: Install Postman
      homebrew_cask:
        state: present
        name: postman
    - name: Install DBeaver Community Edition
      homebrew_cask:
        state: present
        name: dbeaver-community
    - name: Install DockUtil
      homebrew:
        state: present
        name: dockutil
    - name: Install zsh-auto-highlight
      homebrew:
        state: present
        name: zsh-auto-highlighting
    - name: Install zsh-autosuggestions
      homebrew:
        state: present
        name: zsh-autosuggestions
    - name: Install zsh-completions
      homebrew:
        state: present
        name: zsh-completions
    