---
- name: Install Homebrew and Homebrew packages
  connection: local
  hosts: localhost
  vars:
    homebrew_casks:
      - iterm2
      - docker
      - google-cloud-sdk
      - visual-studio-code
      - postman
      - dbeaver-community
      - slack
      - figma
    homebrew_packages:
      - kubectl
      - kubectx
      - kustomize
      - terraform
      - node
      - tilt
      - pre-commit
      - pyenv
      - poetry
      - postgres
      - dockutil
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-completions
  vars_files:
    - ../vars.yml
  pre_tasks:
    - name: Check if homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

  tasks:
    # - name: ensure pexpect is installed
    #   pip:
    #     name: pexpect
    #     state: present
    # - name: Install Homebrew # Install Homebrew
    #   expect:
    #     command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    #     responses:
    #       0: "cd007-01"
    #       1: ""
    #   when:
    #     - not homebrew_check.stat.exists
    # - name: Add homebrew to Path Step 1
    #   shell: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/{{username}}/.zprofile
    #   when:
    #     - not homebrew_check.stat.exists
    # - name: Add homebrew to Path Step 2
    #   shell: eval "$(/opt/homebrew/bin/brew shellenv)"
    #   when:
    #     - not homebrew_check.stat.exists
    - name: Install Homebrew casks
      homebrew_cask:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_casks}}"
    
    - name: Install Homebrew packages
      homebrew:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_packages}}"
    
