---
- name: Install Homebrew and Homebrew packages
  connection: local
  hosts: localhost
  vars:
    homebrew_casks:
      - iterm2
      - docker
      - google-cloud-sdk
      - visual-studio-code
      - postman
      - dbeaver-community
    homebrew_packages:
      - kubectl
      - terraform
      - node
      - dockutil
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-completions
  vars_files:
    - ../vars.yml
  pre_tasks:
    - name: Check if homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

  tasks:
    - name: Install Homebrew # Install Homebrew
      script: ../files/homebrew_install.sh
      when:
        - not homebrew_check.stat.exists
    - name: Add homebrew to Path Step 1
      shell: echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/{{username}}/.zprofile
      when:
        - not homebrew_check.stat.exists
    - name: Add homebrew to Path Step 2
      shell: eval "$(/opt/homebrew/bin/brew shellenv)"
      when:
        - not homebrew_check.stat.exists
    - name: Install Homebrew casks
      homebrew_cask:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_casks}}"
    
    - name: Install zsh-autosuggestions
      homebrew:
        state: present
        name: "{{item}}"
      loop: "{{homebrew_packages}}"
    