---
- name: Install powerline fonts on Mac
  hosts: all
  become: true
  vars:
    powerline_fonts_dir: /Library/Fonts/Powerline
  tasks:
    - name: Install dependencies
      homebrew:
        name: fontconfig
    - name: Clone powerline fonts repository
      git:
        repo: https://github.com/powerline/fonts.git
        dest: /tmp/powerline-fonts
    - name: Install powerline fonts
      command: /tmp/powerline-fonts/install.sh
      args:
        creates: "{{ powerline_fonts_dir }}"
