---
- name: Install pyenv
  hosts: localhost
  tasks:
    - name: Install pyenv
      shell: curl https://pyenv.run | bash
    - name: Write pyenv to zprofile
      blockinfile:
        dest: ~/.zprofile
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
    - name: Write pyenv to zshrc
      lineinfile:
        dest: ~/.zshrc
        line: eval "$(pyenv init -)"