---
- name: Install pyenv
  hosts: localhost
  # pre_tasks:
  #   - name: Check if pyenv is installed
  #     shell: pyenv --version
  #     register: pyenv_check
  tasks:
    - name: Write pyenv to zprofile
      blockinfile:
        dest: ~/.zprofile
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
      # when: pyenv_check.stdout is search("command not found")
    - name: Write pyenv to zshrc
      lineinfile:
        dest: ~/.zshrc
        line: eval "$(pyenv init -)"
      # when: pyenv_check.stdout is search("command not found")