---
- name: Setup VS Code
  hosts: localhost
  vars:
    extensions:
      - ms-python.python
      - ms-vscode-remote.remote-containers
      - ms-azuretools.vscode-docker
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - eamodio.gitlens
      - dbaeumer.vscode-eslint
      - HashiCorp.terraform
      - sourcery.sourcery
      - loiane.angular-extension-pack
  vars_files:
    - ../vars.yml
  tasks:
    - name: Setup code shell command
      lineinfile:
        path: /Users/{{username}}/.zshrc 
        line: export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin" 
    - name: Resource shell
      shell: | 
        export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin" 
    - name: Install VS Code extensions
      shell: | 
        code --install-extension "{{ item }}"
      loop: "{{extensions}}"