---
- name: Generate a new certificate and private key
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Create .ssh directory
      file: 
        path: ~/.ssh
        state: directory
    - name: Generate ssh cert for user
      openssh_keypair:
        path: ~/.ssh/id_rsa
        type: ed25519
        comment: '{{ email_address }}'
    - name: Start ssh agent
      command: eval "$(ssh-agent -s)"
    - name: Ensure config file exists
      file:
        path: ~/.ssh/config
        state: touch
    - name: Write to config file
      copy:
        dest: /User/{{username}}/.ssh/config
        content:
          Host *
            AddKeysToAgent yes
            IdentityFile ~/.ssh/id_rsa
    - name: Add ssh to keychain
      command: ssh-add -K ~/.ssh/id_rsa